# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'vim-airline/vim-airline'

# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'

# [[plugins]]
# repo = 'scrooloose/nerdtree'

# [[plugins]]
# repo = 'Shougo/unite.vim'

# [[plugins]]
# repo = 'tomtom/tcomment_vim'

# [[plugins]]
# repo = 'easymotion/vim-easymotion'

# #[[plugins]]
# #repo = 'itchyny/lightline.vim'

# [[plugins]]
# repo = 'tomasr/molokai'

# [[plugins]]
# repo = 'bronson/vim-trailing-whitespace'

# [[plugins]]
# repo = 'Yggdroot/indentLine'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

# [[plugins]]
# repo = 'dense-analysis/ale'

# [[plugins]]
# repo = 'maximbaz/lightline-ale'
# depends = ['lightline.vim', 'ale']
