# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# コメントアウトをgccでできるように
[[plugins]]
repo = 'tpope/vim-commentary'

# ファイルツリーの表示
[[plugins]]
repo = 'scrooloose/nerdtree'

# surround
[[plugins]]
repo = 'tpope/vim-surround'

# easymotion 
[[plugins]]
repo = 'easymotion/vim-easymotion'

# ステータスバーをいい感じにするやつ
[[plugins]]
repo = 'itchyny/lightline.vim'

# インデント編集
[[plugins]]
repo = 'michaeljsmith/vim-indent-object'

# [[plugins]]
# repo = 'Shougo/unite.vim'


# [[plugins]]
# repo = 'bronson/vim-trailing-whitespace'

# [[plugins]]
# repo = 'Yggdroot/indentLine'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

# [[plugins]]
# repo = 'dense-analysis/ale'

# [[plugins]]
# repo = 'maximbaz/lightline-ale'
# depends = ['lightline.vim', 'ale']
